CREATE DATABASE QLNHANVIEN

GO

USE QLNHANVIEN

GO

--Tạo danh sách nhân viên

CREATE TABLE DSNV
(
	MANV CHAR(7) 	UNIQUE NOT NULL,
	TENVN NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(3) NOT NULL,
	DIACHI NVARCHAR(70) NOT NULL
	PRIMARY KEY(MANV) 
)

INSERT INTO DSNV VALUES ('NV00001' ,N'Trịnh Tú Quyên', N'Nữ', 'Q7, Tp.Hồ Chí Minh')
INSERT INTO DSNV VALUES ('NV00002' ,N'Đỗ Minh Đường', N'Nam', 'Q7, Tp.Hồ Chí Minh')

--Tạo tài khoản nhân viên

CREATE TABLE TKNV
(
	MATK CHAR(8) UNIQUE NOT NULL,
	MANV CHAR(7) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	PRIMARY KEY(MATK)
)

DROP TABLE TKNV
DROP TABLE DSNV

ALTER TABLE TKNV ADD CONSTRAINT FK_DSNV_TKNV FOREIGN KEY(MANV) REFERENCES DSNV

SET DATEFORMAT dmy;

INSERT INTO TKNV VALUES ('51800475', 'NV00001' , '1234567')
INSERT INTO TKNV VALUES ('51900703', 'NV00002' , '1234567')
