//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHOA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_HOA()
        {
            this.PHIEUDATs = new HashSet<PHIEUDAT>();
        }
    
        public string MAHOA { get; set; }
        public string TENHOA { get; set; }
        public string MAUSAC { get; set; }
        public int GIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDAT> PHIEUDATs { get; set; }
    }
}
