//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHOA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDAT
    {
        public string SOPHIEU { get; set; }
        public string MAHOA { get; set; }
        public string MAKHACHHANG { get; set; }
        public string TENNGUOINHAN { get; set; }
        public string DIACHINGUOINHAN { get; set; }
        public string MAKHUVUC { get; set; }
        public System.DateTime NGAYGIAO { get; set; }
        public Nullable<System.TimeSpan> GIOGIAO { get; set; }
        public string DAGIAO { get; set; }
    
        public virtual DM_HOA DM_HOA { get; set; }
        public virtual GIAPHIVANCHUYEN GIAPHIVANCHUYEN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
