//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHOA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKNV
    {
        public string MATK { get; set; }
        public string MANV { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual DSNV DSNV { get; set; }
    }
}
